name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm i
        cd frontend
        npm i
        npm run build
  test:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Test to Production
      run: |
        # Add your test commands here
        echo "Test in Progress"
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Deploy to Production
      run: |
        # Add your deployment commands here
        # This could be deploying to a server, a cloud service, etc.
        pm2 stop ecosystem.config.js
        pm2 start ecosystem.config.js
        pm2 save
        sudo service nginx restart
